CREATE TABLE `fortune_data`.`HorseData` (
  `id` DOUBLE NOT NULL,
  `event_id` DOUBLE NULL,
  `event` VARCHAR(250) NULL,
  `country` VARCHAR(250) NULL,
  `full_description` VARCHAR(250) NULL,
  `course` VARCHAR(250) NULL,
  `scheduled_off` DATETIME NULL,
  `actual_off` DATETIME NULL,
  `selection` VARCHAR(250) NULL,
  `settled_date` DATETIME NULL,
  `odds` DOUBLE NULL,
  `latest_taken` DATETIME NULL,
  `first_taken` DATETIME NULL,
  `in_play` VARCHAR(50) NULL,
  `number_bets` DOUBLE NULL,
  `volume_matched` FLOAT NULL,
  `sports_id` INT NULL,
  `selection_id` INT NULL,
  `win_flag` INT NULL,
  PRIMARY KEY (`id`));